# Configurações de memória e otimização de build
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# AndroidX habilitado
android.useAndroidX=true

# Ativa a nova DSL e o suporte nativo a Kotlin para o AGP recente
android.newDsl=false
android.builtInKotlin=false