name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.5.2
  path_provider: ^2.1.4
  video_player: ^2.8.2
  pdf: ^3.11.1
  printing: ^5.13.4
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Configuração do pacote de ícones
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

# Configuração das imagens/assets do app
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/